%HENONMAP - a script to plot succesive iterates of the Henon map, with
%a set of randomly generated inital coordinates (x, y)
%
% The Henon map maps (x_n, y_n) to (x_(n+1), y_(n+1)) according to the
% equations:
% x_(n+1) = 1 - ax_n^2+y_n
% y_(n+1) = bx_n
%
close all; clear all; clc % close all figures, clear all variables, and clear the command window

numIterations = 10000; % Maximum number of iterations of the map

% Pre-allocate a matrix x with numIterations rows and 100 columns of NaN 
x = NaN(numIterations, 100); 
% Define the first row of x as vector with 100 uniformly distributed rns on (0, 1)
x(1,:) = rand(1,100); 
% Pre-allocate a matrix y with numIterations rows and 100 columns of NaN
y = NaN(numIterations, 100);
% Define the first row of y as vector with 100 uniformly distributed rns on (0, 1)    
y(1,:) = rand(1, 100); %nrows, ncols between (0,1)

% set the parameters a and b

a = 1.4; 
b = 0.3; 

% Iterate the map row-by-row for x and y
for i = 1 : numIterations - 1 
    x(i + 1, :) = 1 - a * x(i, :) .^2 + y(i, :);
    y(i + 1, :) = b*x(i, :);
end

figure(1); clf; hold on
xlabel('$x$','FontName','Times New Roman','Interpreter','Latex')
ylabel('$y$','FontName','Times New Roman','Interpreter','Latex')
%box on
grid on; grid minor
axis equal
title(['Henon Map, a = ' num2str(a) ', b = ' num2str(b)],'FontName','Times New Roman')
set(gca,'FontName','Times New Roman')

% Plot the (x, y) pairs of points generated by the map for the second half 
% of the iterations of the map
for i = floor(numIterations / 2) : numIterations 
    plot(x(i,:), y(i,:), 'k.','MarkerSize',2)
end